### PR TITLE
Adding quiet-askpass to image

### PR DESCRIPTION
**Pull request by trinitronx**
[Helper script][1] to use with `lpass` for quiet password entry.

 - To use, set: `LPASS_ASKPASS='quiet-askpass'`
 - With `docker run`: `-e LPASS_ASKPASS='quiet-askpass'`

[1]: https://lastpass.github.io/lastpass-cli/lpass.1.html#_password_entry

### CODE REVIEW

**Comment by guildencrantz** [comment]
:+1:

**Comment by guildencrantz** [comment]
Sure, the `README` is currently quite sparse, but could you add this to that?

**Comment by trinitronx** [comment]
Yeah, I'll go ahead and document it

**Comment by trinitronx** [comment]
@guildencrantz: How's that look?

**Pull request merged**
